[package]
name = "mfnf_commons"
version = "0.1.0"
authors = ["Valentin Roland <valentin@vroland.de>"]

[dependencies]
mediawiki_parser = "0.3"
mfnf_derive = { path = "derive" }
serde = "1.0"
serde_derive = "1.0"
