[package]
name = "mwparser_utils_derive"
version = "0.1.0"
authors = ["Valentin Roland <valentin@vroland.de>"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.14" , features = ["derive"]} 
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.7"
quote = "0.6"
proc-macro2 = "0.4"
